
services:

  dashboarsihdweb:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5292:8000  # port du server : port de l'application
    volumes:
      - .:/dashboard_mshp-app/
    env_file:
      - ./.env
    restart: always
    depends_on:
      - dashboarsihdDB

  epidemieDB:
    image: postgis/postgis:16-3.4
    platform: linux/amd64
    restart: always
    environment:
      - POSTGRES_USER=ogah
      - POSTGRES_PASSWORD=NEWdimension_MAC@24
      - POSTGRES_DB=epidemie
      - PG_DATA=/data
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    networks:
      - dashboarsih_default

  adminer:
    image: adminer
    restart: always
    ports:
      - 6082:8080
    networks:
      - dashboarsih_default

networks:
  dashboarsih_default:
    external: true

volumes:
  pgdata:
    driver: local
  static_volume:
  media_volume: