services:

  mshpsihweb:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/dashboardmshp-app/
      - static_volume:/app/static
      - media_volume:/app/media
    env_file:
      - ./.env
    restart: always
    depends_on:
      - dashboardDB
    networks:
      - default
      - proxy

    labels:
      - "traefik.enable=true"

      # === ROUTER HTTPS ===
      - "traefik.http.routers.mshpsih.rule=Host(`dashbord.mshpcmu.ci`)"
      - "traefik.http.routers.mshpsih.entrypoints=websecure"
      - "traefik.http.routers.mshpsih.tls=true"
      - "traefik.http.routers.mshpsih.tls.certresolver=lets"
      - "traefik.http.routers.mshpsih.service=mshpsih"

      # === ROUTER HTTP -> HTTPS ===
      - "traefik.http.routers.mshpsih-http.rule=Host(`dashbord.mshpcmu.ci`)"
      - "traefik.http.routers.mshpsih-http.entrypoints=web"
      - "traefik.http.routers.mshpsih-http.middlewares=mshpsih-https"
      - "traefik.http.routers.mshpsih-http.service=mshpsih"
      - "traefik.http.middlewares.mshpsih-https.redirectscheme.scheme=https"

      # === SERVICE backend (Gunicorn HTTP:8000) ===
      - "traefik.http.services.mshpsih.loadbalancer.server.port=8000"
      - "traefik.http.services.mshpsih.loadbalancer.server.scheme=http"
      - "traefik.http.services.mshpsih.loadbalancer.passhostheader=true"

      # Traefik doit utiliser ce réseau
      - "traefik.docker.network=proxy"
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsS -H 'Host: dashbord.mshpcmu.ci' http://127.0.0.1:8000/healthz || exit 1" ]
      interval: 30s
      timeout: 5s
      retries: 3

  dashboardDB:
    image: postgis/postgis:16-3.4
    platform: linux/amd64
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - default

  adminersih:
    image: adminer
    restart: always
    networks:
      - default
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mshpsih.rule=Host(`dashbord.mshpcmu.ci`)"
      - "traefik.http.routers.mshpsih.entrypoints=websecure"
      - "traefik.http.routers.mshpsih.tls=true"
      - "traefik.http.routers.mshpsih.tls.certresolver=lets"
      - "traefik.http.routers.mshpsih-http.rule=Host(`dashbord.mshpcmu.ci`)"
      - "traefik.http.routers.mshpsih-http.entrypoints=web"
      - "traefik.http.routers.mshpsih-http.middlewares=mshpsih-https"
      - "traefik.http.middlewares.mshpsih-https.redirectscheme.scheme=https"
      - "traefik.http.services.mshpsih.loadbalancer.server.port=8000"
      - "traefik.docker.network=proxy"
networks:
  default:
  proxy:
    external: true

volumes:
  traefik_letsencrypt: { }
  pgdata:
    driver: local
  static_volume:
  media_volume:


#services:
#
#  dashboardsihdweb:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - 5292:8000  # port du server : port de l'application
#    volumes:
#      - .:/dashboardmshp-app/
#    env_file:
#      - ./.env
#    restart: always
#    depends_on:
#      - dashboardDB
#
#  dashboardDB:
#    image: postgis/postgis:16-3.4
#    platform: linux/amd64
#    restart: always
#    environment:
#      - POSTGRES_USER=ogah
#      - POSTGRES_PASSWORD=NEWdimension_MAC@24
#      - POSTGRES_DB=dashboard
#      - PG_DATA=/data
#    volumes:
#      - pgdata:/var/lib/postgresql/data
#
#  nginx:
#    image: nginx:latest
#    container_name: nginx-proxy
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf
#      - ./certs:/etc/nginx/certs
#    networks:
#      - dashboardsih_default
#
#  adminersih:
#    image: adminer
#    restart: always
#    ports:
#      - 6082:8080
#    networks:
#      - dashboardsih_default
#
#networks:
#  dashboardsih_default:
#    external: true
#
#volumes:
#  pgdata:
#    driver: local
#  static_volume:
#  media_volume: