# Generated by Django 4.2.15 on 2024-10-02 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyntheseActivites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_visite', models.IntegerField(blank=True, null=True, verbose_name='Total Visite')),
                ('total_recette', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total Recette')),
                ('total_recouvrement', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total Recouvrement')),
                ('total_gratuite_ciblee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total Gratuité Ciblée')),
                ('total_cas_sociaux', models.IntegerField(blank=True, null=True, verbose_name='Total Cas Sociaux')),
                ('total_acte_reduit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total Acte Réduit')),
                ('total_cmu', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total CMU')),
                ('total_hors_cmu', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total Hors CMU')),
                ('date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('deleted_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('centre_sante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dash.servicesanitaire')),
            ],
        ),
    ]
