# Generated by Django 4.2.15 on 2025-03-05 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
    ]
