# Generated by Django 4.2.15 on 2024-10-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeservicesanitaire',
            name='nom',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
