# Generated by Django 4.2.15 on 2024-10-02 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0003_poles_regionaux_healthregion_poles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='poles_regionaux',
            new_name='PolesRegionaux',
        ),
    ]
